sonar.projectKey=ecomm-orbital-widget-js

# Path is relative to the sonar-project.properties file. Defaults to .
sonar.sources=src

# Excluded src files and folders
sonar.exclusions=**/*.test.ts,\
                **/*.test.tsx,\
                **/*.d.ts,\
                **/examples/**,\
                **/dist/**/*,\
                **/lib/**/*,\
                **/build/**/*,\
                **/node_modules/**/*

# Tests - Comma separated list of folders containing tests
sonar.tests=tests
sonar.test.inclusions=**/*.test.ts,**/*.test.tsx

# Add coverage results
sonar.javascript.lcov.reportPaths=coverage/lcov.info

sonar.typescript.tsconfigPath=tsconfig.json

# Dependency Check configuration
sonar.dependencyCheck.jsonReportPath=reports/dependency-check-report.json
sonar.dependencyCheck.htmlReportPath=reports/dependency-check-report.html
sonar.dependencyCheck.format=JSON
