name: Dependabot Jira Ticket

on:
  pull_request:
    types: [closed]
    branches: [dev]

permissions:
  pull-requests: write
  contents: read

jobs:
  jira-ticket:
    name: Create Jira Ticket
    if: github.event.pull_request.user.login == 'dependabot[bot]' && github.event.pull_request.merged == true
    uses: PayConstruct/github-actions-workflows/.github/workflows/dependabot-jira-ticket.yml@main
    with:
      jira-project-key: "PMCR"
      production-branch: "main"
      jira-issue-type: "Ops"
      jira-base-url: "https://getorbital.atlassian.net"
    secrets:
      JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
      JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
