name: Deploy package to GitHub package registry

on:
  workflow_call:
    inputs:
      branch_name:
        required: true
        description: The branch name triggering the workflow
        type: string
    secrets:
      base_url_tst:
        required: false
        description: Optional Base URL for the 'tst' environment
      base_url:
        required: false
        description: Optional Base URL for other environments
      deploy_token:
        required: true
        description: GitHub deploy token
      org_npmrc:
        required: true
        description: .npmrc secret for GitHub Packages authentication
      protected_branch_reviewer_token:
        required: true
        description: Protected branch reviewer token
      npm_token:
        required: true
        description: NPM registry publish token

permissions:
  id-token: write
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, 'ci skip') && !contains(github.event.head_commit.message, 'skip ci') }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
          token: ${{ secrets.deploy_token }}

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: yarn-deps-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            yarn-deps-${{ hashFiles('yarn.lock') }}

      - name: Use .npmrc
        uses: bduff9/use-npmrc@v2.0.0
        with:
          dot-npmrc: ${{ secrets.org_npmrc }}

      - name: Set Git Identity
        run: |
          git config --global user.email "github-bot@getorbital.com"
          git config --global user.name "getorbital-bot"
          git fetch --unshallow --tags

      - name: Set env (optional)
        id: setEnv
        run: |
          if [ "${{ inputs.branch_name }}" == "dev" ]; then
            echo base-url=${{ secrets.base_url_tst }} >> $GITHUB_OUTPUT
          else
            echo base-url=${{ secrets.base_url }} >> $GITHUB_OUTPUT
          fi
      - name: Build project
        env:
          BASE_URL: ${{ steps.setEnv.outputs.base-url }}
        run: |
          yarn build
      - name: Update version and publish
        env:
          GITHUB_TOKEN: ${{ secrets.deploy_token }}
          NODE_AUTH_TOKEN: ${{ secrets.deploy_token }}
          NPM_TOKEN: ${{ secrets.npm_token }}
          PROTECTED_BRANCH_REVIEWER_TOKEN: ${{ secrets.protected_branch_reviewer_token }}
        run: |
          if [ "${{ inputs.branch_name }}" == "dev" ]; then
            yarn auto canary --force
          else 
            yarn auto shipit --base-branch=main
          fi

      - name: Update example packages
        env:
          GITHUB_TOKEN: ${{ secrets.deploy_token }}
          NODE_AUTH_TOKEN: ${{ secrets.deploy_token }}
          NPM_TOKEN: ${{ secrets.npm_token }}
        run: |
          yarn run update-examples:all

      - name: Commit updated examples
        env:
          GITHUB_TOKEN: ${{ secrets.deploy_token }}
          NODE_AUTH_TOKEN: ${{ secrets.deploy_token }}
          NPM_TOKEN: ${{ secrets.npm_token }}
        run: |
          git config --global user.email "github-bot@getorbital.com"
          git config --global user.name "getorbital-bot"
          git add ./examples/react/package.json ./examples/rollup/package.json

          # Check if there are any changes to commit
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "chore: ci skip update examples with latest version."

            # Create a new branch to push changes
            git checkout -b update-version-examples-branch
            git push -u origin update-examples-branch

      - name: Create pull request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.deploy_token }}
          commit-message: 'chore: ci skip update examples with latest version.'
          branch: update-version-examples-branch
          base: ${{ inputs.branch_name }}
          title: 'Update example packages'
          body: 'Auto-generated PR to update example packages.'

      - name: Approve and merge pull request
        if: success()
        uses: pascalgn/automerge-action@v0.15.3
        env:
          GITHUB_TOKEN: ${{ secrets.protected_branch_reviewer_token }}
        with:
          approve: true
          merge-method: squash
          merge-message: 'chore: auto-merge after package update'

      - name: Delete branch after merge
        if: success()
        run: |
          BRANCH_NAME=update-version-examples-branch
          curl -X DELETE \
            -H "Authorization: token ${{ secrets.deploy_token }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/git/refs/heads/$BRANCH_NAME
