name: Deploy package to GitHub package registry

on:
  workflow_call:
    inputs:
      branch_name:
        required: true
        description: The branch name triggering the workflow
        type: string
    secrets:
      base_url_tst:
        required: false
        description: Optional Base URL for the 'tst' environment
      base_url:
        required: false
        description: Optional Base URL for other environments
      deploy_token:
        required: true
        description: GitHub deploy token
      org_npmrc:
        required: true
        description: .npmrc secret for GitHub Packages authentication
      protected_branch_reviewer_token:
        required: true
        description: Protected branch reviewer token
      npm_token:
        required: true
        description: NPM registry publish token

permissions:
  id-token: write
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, 'ci skip') && !contains(github.event.head_commit.message, 'skip ci') }}

    env:
      BRANCH_NAME: update-version-examples-branch # Define the branch name as an environment variable

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
          token: ${{ secrets.deploy_token }}

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: yarn-deps-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            yarn-deps-${{ hashFiles('yarn.lock') }}

      - name: Use .npmrc
        uses: bduff9/use-npmrc@v2.0.0
        with:
          dot-npmrc: ${{ secrets.org_npmrc }}

      - name: Set Git Identity
        run: |
          git config --global user.email "github-bot@getorbital.com"
          git config --global user.name "getorbital-bot"
          git fetch --unshallow --tags

      - name: Set env (optional)
        id: setEnv
        run: |
          if [ "${{ inputs.branch_name }}" == "dev" ]; then
            echo base-url=${{ secrets.base_url_tst }} >> $GITHUB_OUTPUT
          else
            echo base-url=${{ secrets.base_url }} >> $GITHUB_OUTPUT
          fi
      - name: Build project
        env:
          BASE_URL: ${{ steps.setEnv.outputs.base-url }}
        run: |
          yarn build
      - name: Update version and publish
        env:
          GITHUB_TOKEN: ${{ secrets.deploy_token }}
          NODE_AUTH_TOKEN: ${{ secrets.deploy_token }}
          NPM_TOKEN: ${{ secrets.npm_token }}
          PROTECTED_BRANCH_REVIEWER_TOKEN: ${{ secrets.protected_branch_reviewer_token }}
        run: |
          if [ "${{ inputs.branch_name }}" == "dev" ]; then
            yarn auto canary --force
          else 
            yarn auto shipit --base-branch=main
          fi

      - name: Update example packages and Commit updated examples
        env:
          GITHUB_TOKEN: ${{ secrets.deploy_token }}
          NODE_AUTH_TOKEN: ${{ secrets.deploy_token }}
          NPM_TOKEN: ${{ secrets.npm_token }}
        run: |
          git config --global user.email "github-bot@getorbital.com"
          git config --global user.name "getorbital-bot"

          # Update examples
          yarn run update-examples:all

          # Add changes changes
          git add ./examples/react/package.json ./examples/rollup/package.json

          # Check if there are any changes to commit
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "chore: ci skip update examples with latest version."
            # Create a new branch to push changes and push
            git checkout -b ${BRANCH_NAME}
            git push -u origin ${BRANCH_NAME}
          fi

      - name: Create pull request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.deploy_token }}
          commit-message: 'chore: automerge ci skip update examples with latest version.'
          branch: ${{ env.BRANCH_NAME }}
          base: ${{ inputs.branch_name }}
          title: 'chore: automerge ci skip update examples with latest version.'
          body: 'Auto-generated PR to update example version packages.'

      - name: Approve and merge pull request
        id: automerge
        uses: 'pascalgn/automerge-action@v0.16.4'
        env:
          GITHUB_TOKEN: ${{ secrets.protected_branch_reviewer_token }}
          MERGE_METHOD: 'squash'
          MERGE_COMMIT_MESSAGE: 'chore: automerge ci skip update examples with latest version.'
          MERGE_FORKS: 'false'
          MERGE_RETRIES: '6'
          MERGE_RETRY_SLEEP: '10000'
          MERGE_REQUIRED_APPROVALS: '0'
          MERGE_DELETE_BRANCH: true
          BASE_BRANCHES: 'main,dev'

      - name: feedback
        if: ${{ steps.automerge.outputs.mergeResult == 'merged' }}
        run: |
          echo "Pull request ${{ steps.automerge.outputs.pullRequestNumber }} merged!"
