name: sonarqube

on:
  push:
    branches:
      - dev

permissions:
  id-token: write
  contents: read

jobs:
  sonarqube:
    uses: PayConstruct/github-actions-workflows/.github/workflows/sonarqube.yml@main
    with:
      aws-region: eu-west-1
      full-repo-name: ${{ github.repository }}
    secrets: inherit
